header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: github.com/chgl

  paths-ignore:
    - "**/*.md"
    - "LICENSE"
    - "**/.*"
    - "**/*.json"
    - "**/*.gotmpl"
    - "**/*.txt"

  comment: on-failure

dependency:
  files:
    - package.json
    - requirements.txt
